module.exports = {
  easy: [
    "What is Node.js and is it a programming language?",
    "What is Express and why is it used with Node.js?",
    "Explain the difference between Node.js and a web browser.",
    "What is NPM (Node Package Manager) and how do you use it?",
    "What is the purpose of the 'package.json' file?",
    "Explain the difference between 'require' and 'import'.",
    "What are Global Objects in Node.js?",
    "How do you create a simple server in Node.js without Express?",
    "What is the 'fs' module in Node.js used for?",
    "What is the difference between 'path.join()' and 'path.resolve()'?",
  ],
  moderate: [
    "Explain Middleware in Express and its three arguments (req, res, next).",
    "What is a REST API and what are the main HTTP methods?",
    "Explain the difference between 'setImmediate()' and 'process.nextTick()'.",
    "How do you handle error management in Express middleware?",
    "What is the 'Event Emitter' in Node.js and how does it work?",
    "Explain the difference between 'body-parser' and built-in Express JSON parsing.",
    "What are Environment Variables and why are they important?",
    "How do you handle file uploads in an Express application?",
    "Explain the concept of 'Streams' in Node.js.",
    "What is the difference between 'app.use()' and 'app.all()' in Express?",
  ],
  hard: [
    "Explain the JWT (JSON Web Token) authentication flow in detail.",
    "How would you scale a Node.js server (Vertical vs. Horizontal scaling)?",
    "Explain the 'Cluster' module and how it utilizes multi-core systems.",
    "What is 'Garbage Collection' in V8 and how can you detect memory leaks?",
    "Explain 'Worker Threads' and when to use them over the Cluster module.",
    "How do you handle 'Callback Hell' and what are the modern alternatives?",
    "Explain the 'Backpressure' concept in Node.js Streams.",
    "How would you implement a 'Rate Limiter' in an Express application?",
    "Explain the difference between 'WebSocket' and 'Long Polling'.",
    "How do you secure a Node.js API (CORS, Helmet, Sanitization)?",
  ],
};
