module.exports = {
  easy: [
    "What is data analysis and why is it important in business?",
    "What is the difference between structured and unstructured data?",
    "What is Excel used for in data analysis and what are its limitations?",
    "What is SQL and why is it essential for data analysts?",
    "What is a Primary Key and a Foreign Key in a database?",
    "Explain the difference between Qualitative and Quantitative data.",
    "What is a CSV file and why is it commonly used?",
    "What are the basic aggregate functions in SQL (SUM, AVG, COUNT, etc.)?",
    "What is a pivot table in Excel?",
    "What is the difference between a Data Analyst and a Data Scientist?",
  ],
  moderate: [
    "Explain the GROUP BY clause in SQL and how it differs from WHERE.",
    "What is data cleaning and what are common steps involved?",
    "What is database normalization and what problem does it solve?",
    "Explain the difference between INNER JOIN, LEFT JOIN, and RIGHT JOIN.",
    "What is Exploratory Data Analysis (EDA) and what are its goals?",
    "How do you handle missing or null values in a dataset?",
    "What is an Outlier and how can it affect your analysis?",
    "Explain the difference between a dimension and a measure in BI tools.",
    "How do you use the VLOOKUP or XLOOKUP function in Excel?",
    "What is a subquery in SQL and when would you use one?",
  ],
  hard: [
    "Explain how you would analyze a large dataset to identify long-term trends.",
    "What is the difference between correlation and causation? Give an example.",
    "Explain indexing in databases and how it impacts query performance.",
    "How would you optimize a slow-running SQL query?",
    "Explain the steps in building an effective data visualization dashboard.",
    "What is a CTE (Common Table Expression) and how does it improve code readability?",
    "Explain 'Window Functions' in SQL (like ROW_NUMBER or RANK).",
    "How do you deal with 'Data Leakage' in the context of predictive analysis?",
    "Describe the difference between A/B testing and multivariate testing.",
    "Explain the concept of 'Data Warehousing' versus a 'Data Lake'.",
  ],
};
