module.exports = {
  easy: [
    "What is HTML and what are semantic tags?",
    "What is the difference between var, let, and const?",
    "Explain the different data types in JavaScript.",
    "What is CSS Flexbox and how do you center a div?",
    "What is the purpose of the 'alt' attribute in images?",
    "What is the difference between '==' and '==='?",
    "What are arrow functions and how do they differ from regular functions?",
    "Explain the concept of 'Hoisting' in JavaScript.",
    "What is the difference between an ID and a Class in CSS?",
    "What is NPM and what is the purpose of package.json?",
  ],
  moderate: [
    "Explain the React Virtual DOM and how it differs from the Real DOM.",
    "How does the useEffect hook work and what is the dependency array?",
    "Explain Event Delegation and Event Bubbling in JavaScript.",
    "What is the difference between State and Props in React?",
    "How does 'this' keyword work in JavaScript?",
    "Explain Promises and the difference between .then() and async/await.",
    "What are Higher-Order Components (HOC) in React?",
    "Explain the concept of Closures in JavaScript.",
    "How does the 'Context API' differ from 'Redux' for state management?",
    "What is the difference between localStorage, sessionStorage, and Cookies?",
  ],
  hard: [
    "Explain the React Reconciliation algorithm (Diffing algorithm).",
    "How would you optimize a large-scale React application for performance?",
    "Explain Server-Side Rendering (SSR) vs Client-Side Rendering (CSR).",
    "What is the 'Event Loop' in Node.js and how does it handle asynchronous code?",
    "Explain the concept of Currying in functional programming.",
    "How do you handle memory leaks in a React application?",
    "Explain the difference between Prototypal and Classical inheritance.",
    "How does the 'useMemo' hook differ from 'useCallback', and when should you use them?",
    "What are Web Workers and how do they help in heavy computations?",
    "Explain the 'Dependency Injection' pattern and its use cases in backend development.",
  ],
};
