module.exports = {
  easy: [
    "What is the difference between frontend and backend development?",
    "What is a REST API and what does 'Statelessness' mean in this context?",
    "What is JSON and why is it the preferred format for data exchange?",
    "What is a database and the difference between SQL and NoSQL?",
    "Explain the Client-Server architecture model.",
    "What is the purpose of a Web Server versus an Application Server?",
    "What is an IP address and a Domain Name?",
    "What does 'CRUD' stand for in web development?",
    "What is the role of an API Gateway?",
    "What are HTTP Status Codes (e.g., 200, 404, 500) and why are they used?",
  ],
  moderate: [
    "Explain how authentication works in a full stack application from login to logout.",
    "What is JWT (JSON Web Token) and where should it be stored on the client side?",
    "How do you connect a React frontend with a Node.js backend using Axios or Fetch?",
    "Explain the MVC (Model-View-Controller) architecture pattern.",
    "What is CORS and why do we encounter it when connecting frontend to backend?",
    "Explain the difference between Session-based and Token-based authentication.",
    "What are Environment Variables (.env) and why are they never pushed to GitHub?",
    "How do you handle data validation on both the frontend and the backend?",
    "Explain the concept of 'Middleware' in the context of a full-stack request.",
    "What is the difference between Authentication and Authorization?",
  ],
  hard: [
    "Design a scalable full stack application architecture (Load Balancers, Caching, etc.).",
    "How would you implement Role-Based Access Control (RBAC) in a MERN app?",
    "Explain Microservices vs. Monolithic architecture: Pros and Cons.",
    "How would you optimize performance in a MERN stack app (Indexing, Memoization, Compression)?",
    "Explain state management strategies in large React applications (Redux, Context, React Query).",
    "How do you handle 'Race Conditions' when multiple users update the same database record?",
    "Explain the 'Double-Submit Cookie' pattern or other CSRF protection methods.",
    "How would you implement Real-time features (like Chat) using WebSockets in a MERN stack?",
    "Explain Database Sharding and Replication for high-traffic applications.",
    "How do you implement CI/CD pipelines for a full-stack application deployment?",
  ],
};
