module.exports = {
  easy: [
    "Tell me about yourself and your journey in Computer Engineering.",
    "Why should we hire you over other candidates?",
    "What are your greatest strengths and weaknesses?",
    "What do you know about our company and why do you want to work here?",
    "Are you comfortable working in a remote or hybrid environment?",
    "What are your salary expectations as a fresh graduate?",
    "How do you stay updated with the latest technology trends?",
    "What is your preferred programming language and why?",
    "Describe your ideal work environment.",
    "Do you have any questions for us?",
  ],
  moderate: [
    "Describe a significant technical challenge you faced and how you solved it.",
    "Where do you see yourself professionally in 5 years?",
    "How do you prioritize your tasks when you have multiple deadlines?",
    "Describe a project you are most proud of and your specific role in it.",
    "How do you handle working under pressure or tight timelines?",
    "Give an example of a time you had to learn a new technology quickly.",
    "What would you do if you were asked to perform a task you've never done before?",
    "How do you handle feedback or constructive criticism?",
    "What motivates you to come to work every day?",
    "Describe a time you went above and beyond for a project or task.",
  ],
  hard: [
    "Describe a major failure in your career/projects and what you learned from it.",
    "How do you handle conflict or a difference of opinion within a team?",
    "Tell me about a time you had to deal with a difficult team member.",
    "Describe a situation where you had to lead a team or take initiative.",
    "What would you do if you realized a project was going to miss its deadline?",
    "Explain a complex technical concept to a non-technical person.",
    "Describe a time you had to make an unpopular decision for the sake of the project.",
    "How do you handle ambiguity or shifting requirements in a project?",
    "Tell me about a time you disagreed with a supervisor’s decision. How did you handle it?",
    "If you are hired and find that the job isn't what you expected, what would you do?",
  ],
};
